name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Initialize Python 3.11
      uses: actions/setup-python@v1
      with:
          python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --dev
    - name: Analysing the code with pylint
      run: |
        pipenv run pylint --errors-only oktaawscli
